## Ejemplo 5: Filtros

### 1. Objetivos:
    - Aprender cómo funcionan los filtros
    - Aplicar varios filtros para verlos en acción
 
### 2. Desarrollo:

In [1]:
import pandas as pd

Creamos nuestro DataFrame a partir del archivo de datos CSV:

In [2]:
df = pd.read_csv('../../Datasets/new_york_times_bestsellers-dirty.csv', index_col=0)

df.head(3)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
0,http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Descr: Aliens have taken control of the minds ...,"Little, Brown",THE HOST,5b4aa4ead3089013507db18c,2008-05-24 00:00:00,1212883200000,2,1,3,25.99
1,http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,Descr: A woman's happy marriage is shaken when...,St. Martin's,LOVE THE ONE YOU'RE WITH,5b4aa4ead3089013507db18d,2008-05-24 00:00:00,1212883200000,3,2,2,24.95
2,http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,Descr: A Massachusetts state investigator and ...,Putnam,THE FRONT,5b4aa4ead3089013507db18e,2008-05-24 00:00:00,1212883200000,4,0,1,22.95

Ahora, queremos todos los registros donde el nombre del autor empiece con 'R', entonces usamos la función `str.startswith(-patrón-)` a la columna `author` de la forma:

`df[-columna-].str.startswith(-patrón-)`

In [3]:
df["author"].str.startswith('R')

0       False
1       False
2       False
3       False
5       False
        ...
3027    False
3028    False
3029    False
3030    False
3031    False
Name: author, Length: 2266, dtype: bool

Lo que obtenemos de regreso es una `Serie` con la misma longitud que la columna original y la función `startswith()` se aplicó comparando cada elemento regresando un valor booleano.

Después, al pasar este filtro al `operador de indexación` del `DataFrame`, todas las filas a las que les corresponda un `True` se mantienen, mientras que las filas a las que les corresponde un `False` se dejan fuera del subconjunto resultante:

`dataframe[ -serie índice para filtrado- ]`

In [8]:
df[df["author"].str.startswith('R')]

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
79,http://www.amazon.com/Chasing-Darkness-Elvis-N...,Robert Crais,Descr: he Los Angeles private eye Elvis Cole r...,Simon & Schuster,CHASING DARKNESS,5b4aa4ead3089013507db209,2008-07-05 00:00:00,1216512000000,7,0,1,25.95
94,http://www.amazon.com/Chasing-Darkness-Elvis-N...,Robert Crais,Descr: Is the Los Angeles private eye Elvis Co...,Simon & Schuster,CHASING DARKNESS,5b4aa4ead3089013507db221,2008-07-12 00:00:00,1217116800000,11,7,2,25.95
110,http://www.amazon.com/Killer-View-Fleming-Ridl...,Ridley Pearson,"Descr: A sheriff in Sun Valley, Idaho, investi...",Putnam,KILLER VIEW,5b4aa4ead3089013507db239,2008-07-19 00:00:00,1217721600000,15,0,1,24.95
143,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db26f,2008-08-09 00:00:00,1219536000000,9,0,1,25.95
158,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db287,2008-08-16 00:00:00,1220140800000,No Rank,9,2,25.95
173,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db29c,2008-08-23 00:00:00,1220745600000,14,13,3,25.95
643,http://www.amazon.com/The-Sign-Raymond-Khoury/...,Raymond Khoury,Descr: Is an apparition that has been seen aro...,Dutton,THE SIGN,5b4aa4ead3089013507db5a3,2009-05-23 00:00:00,1244332800000,No Rank,0,1,26.95
660,http://www.amazon.com/The-Sign-Raymond-Khoury/...,Raymond Khoury,Descr: Is an apparition that has been seen aro...,Dutton,THE SIGN,5b4aa4ead3089013507db5bc,2009-05-30 00:00:00,1244937600000,14,9,2,26.95
777,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with thei...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db678,2009-08-08 00:00:00,1250985600000,No Rank,0,1,25.95
793,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with thei...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db68e,2009-08-15 00:00:00,1251590400000,4,2,2,25.95
804,http://www.amazon.com/Intervention-Robin-Cook/...,Robin Cook,Descr: A potentially explosive archaeological ...,Putnam,INTERVENTION,5b4aa4ead3089013507db699,2009-08-15 00:00:00,1251590400000,15,0,1,25.95
808,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6a3,2009-08-22 00:00:00,1252195200000,5,4,3,25.95
824,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6b9,2009-08-29 00:00:00,1252800000000,No Rank,5,4,25.95
843,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6d3,2009-09-05 00:00:00,1253404800000,13,7,5,25.95
858,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6e9,2009-09-12 00:00:00,1254009600000,15,13,6,25.95
872,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6fd,2009-09-19 00:00:00,1254614400000,15,15,7,25.95
922,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db749,2009-10-17 00:00:00,1257033600000,11,0,1,19.99
929,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db758,2009-10-24 00:00:00,1257638400000,No Rank,11,2,19.99
957,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db789,2009-11-07 00:00:00,1258848000000,15,0,3,19.99
965,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db799,2009-11-14 00:00:00,1259452800000,11,15,4,19.99
980,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db7b0,2009-11-21 00:00:00,1260057600000,14,11,5,19.99
1062,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \nElvis Cole and his partner, Joe Pike,...",Penguin Group (USA) Incorporated,THE FIRST RULE,5b4aa4ead3089013507db844,2010-01-17 00:00:00,1264896000000,2,0,1,26.95
1080,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db85b,2010-01-24 00:00:00,1265500800000,5,2,2,26.95
1093,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db86f,2010-01-31 00:00:00,1266105600000,5,5,3,26.95
1114,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db88a,2010-02-07 00:00:00,1266710400000,12,5,4,26.95
1442,http://www.amazon.com/Cure-Robin-Cook/dp/03991...,Robin Cook,Descr: \nA New York City medical examiner atte...,Putnam,CURE,5b4aa4ead3089013507dbaa8,2010-08-15 00:00:00,1283040000000,14,0,1,26.95
1530,http://www.amazon.com/Naked-Heat-Nikki-Richard...,Richard Castle,Descr: Nikki Heat’s latest murder investigatio...,Hyperion,NAKED HEAT,5b4aa4ead3089013507dbb2d,2010-10-03 00:00:00,1287273600000,7,0,1,24.99
1549,http://www.amazon.com/Naked-Heat-Nikki-Richard...,Richard Castle,Descr: Nikki Heat’s latest murder investigatio...,Hyperion,NAKED HEAT,5b4aa4ead3089013507dbb4a,2010-10-10 00:00:00,1287878400000,16,7,2,24.99
1575,http://www.amazon.com/The-Templar-Salvation-Ra...,Raymond Khoury,Descr: A secret history of the infamous Templa...,Dutton,THE TEMPLAR SALVATION,5b4aa4ead3089013507dbb72,2010-10-24 00:00:00,1289088000000,16,0,1,26.95
1717,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,"Descr: Joe Pike and Elvis Cole, Hollywood priv...",Putnam,THE SENTRY,5b4aa4ead3089013507dbc54,2011-01-16 00:00:00,1296345600000,2,0,1,26.95
1733,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,"Descr: Joe Pike and Elvis Cole, Hollywood priv...",Putnam,THE SENTRY,5b4aa4ead3089013507dbc6b,2011-01-23 00:00:00,1296950400000,5,2,2,26.95
1748,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbc82,2011-01-30 00:00:00,1297555200000,8,5,3,26.95
1763,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbc99,2011-02-05 00:00:00,1298160000000,11,8,4,26.95
1778,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbcb0,2011-02-12 00:00:00,1298764800000,No Rank,11,5,26.95
2147,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf23,2011-09-24 00:00:00,1318118400000,1,0,1,25.99
2167,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf40,2011-10-01 00:00:00,1318723200000,10,1,2,25.99
2191,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf6a,2011-10-15 00:00:00,1319932800000,12,0,3,25.99
2350,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc08b,2012-01-28 00:00:00,1329004800000,1,0,1,26.95
2364,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0a1,2012-02-04 00:00:00,1329609600000,3,1,2,26.95
2370,http://www.amazon.com/The-Fear-Index-Robert-Ha...,Robert Harris,Descr: A billionaire hedge fund manager in Gen...,Knopf,THE FEAR INDEX,5b4aa4ead3089013507dc0aa,2012-02-04 00:00:00,1329609600000,12,0,1,25.95
2378,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0ba,2012-02-11 00:00:00,1330214400000,8,3,3,26.95
2384,http://www.amazon.com/The-Fear-Index-Robert-Ha...,Robert Harris,Descr: A billionaire hedge fund manager in Gen...,Knopf,THE FEAR INDEX,5b4aa4ead3089013507dc0c1,2012-02-11 00:00:00,1330214400000,15,12,2,25.95
2394,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0d4,2012-02-18 00:00:00,1330819200000,14,8,4,26.95
2469,http://www.amazon.com/The-Cove-Novel-Ron-Rash/...,Ron Rash,Descr: Intrigue in backwoods North Carolina du...,Ecco/HarperCollins,THE COVE,5b4aa4ead3089013507dc176,2012-04-14 00:00:00,1335657600000,16,0,1,26.99
2536,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc1e6,2012-05-26 00:00:00,1339286400000,8,0,1,27.99
2546,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc1fe,2012-06-02 00:00:00,1339891200000,12,8,2,27.99
2559,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc216,2012-06-09 00:00:00,1340496000000,16,12,3,27.99
2563,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc220,2012-06-16 00:00:00,1341100800000,6,16,4,27.99
2571,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc233,2012-06-23 00:00:00,1341705600000,5,6,5,27.99
2582,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc24b,2012-06-30 00:00:00,1342310400000,9,5,6,27.99
2594,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc262,2012-07-07 00:00:00,1342915200000,12,9,7,27.99
2692,http://www.amazon.com/Frozen-Heat-Nikki-Richar...,Richard Castle,Descr: The N.Y.P.D. homicide detective Nikki H...,Hyperion,FROZEN HEAT,5b4aa4ead3089013507dc326,2012-09-15 00:00:00,1348963200000,8,0,1,26.99
2891,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc49d,2013-01-26 00:00:00,1360454400000,3,0,1,27.95
2905,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4b4,2013-02-02 00:00:00,1361059200000,No Rank,3,2,27.95
2918,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4c9,2013-02-09 00:00:00,1361664000000,No Rank,6,3,27.95
2930,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4dd,2013-02-16 00:00:00,1362268800000,7,7,4,27.95
2945,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4f7,2013-02-23 00:00:00,1362873600000,13,7,5,27.95

In [24]:
df[df["author"].str.lower().str.startswith('r')]

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
79,http://www.amazon.com/Chasing-Darkness-Elvis-N...,Robert Crais,Descr: he Los Angeles private eye Elvis Cole r...,Simon & Schuster,CHASING DARKNESS,5b4aa4ead3089013507db209,2008-07-05 00:00:00,1216512000000,7,0,1,25.95
94,http://www.amazon.com/Chasing-Darkness-Elvis-N...,Robert Crais,Descr: Is the Los Angeles private eye Elvis Co...,Simon & Schuster,CHASING DARKNESS,5b4aa4ead3089013507db221,2008-07-12 00:00:00,1217116800000,11,7,2,25.95
110,http://www.amazon.com/Killer-View-Fleming-Ridl...,Ridley Pearson,"Descr: A sheriff in Sun Valley, Idaho, investi...",Putnam,KILLER VIEW,5b4aa4ead3089013507db239,2008-07-19 00:00:00,1217721600000,15,0,1,24.95
143,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db26f,2008-08-09 00:00:00,1219536000000,9,0,1,25.95
158,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db287,2008-08-16 00:00:00,1220140800000,No Rank,9,2,25.95
173,http://www.amazon.com/Foreign-Body-Robin-Cook/...,Robin Cook,Descr: A medical student investigates a rising...,Putnam,FOREIGN BODY,5b4aa4ead3089013507db29c,2008-08-23 00:00:00,1220745600000,14,13,3,25.95
643,http://www.amazon.com/The-Sign-Raymond-Khoury/...,Raymond Khoury,Descr: Is an apparition that has been seen aro...,Dutton,THE SIGN,5b4aa4ead3089013507db5a3,2009-05-23 00:00:00,1244332800000,No Rank,0,1,26.95
660,http://www.amazon.com/The-Sign-Raymond-Khoury/...,Raymond Khoury,Descr: Is an apparition that has been seen aro...,Dutton,THE SIGN,5b4aa4ead3089013507db5bc,2009-05-30 00:00:00,1244937600000,14,9,2,26.95
777,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with thei...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db678,2009-08-08 00:00:00,1250985600000,No Rank,0,1,25.95
793,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with thei...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db68e,2009-08-15 00:00:00,1251590400000,4,2,2,25.95
804,http://www.amazon.com/Intervention-Robin-Cook/...,Robin Cook,Descr: A potentially explosive archaeological ...,Putnam,INTERVENTION,5b4aa4ead3089013507db699,2009-08-15 00:00:00,1251590400000,15,0,1,25.95
808,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6a3,2009-08-22 00:00:00,1252195200000,5,4,3,25.95
824,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6b9,2009-08-29 00:00:00,1252800000000,No Rank,5,4,25.95
843,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6d3,2009-09-05 00:00:00,1253404800000,13,7,5,25.95
858,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6e9,2009-09-12 00:00:00,1254009600000,15,13,6,25.95
872,http://www.amazon.com/That-Cape-Magic-Richard-...,Richard Russo,Descr: A long-married couple wrestle with diss...,Knopf,THAT OLD CAPE MAGIC,5b4aa4ead3089013507db6fd,2009-09-19 00:00:00,1254614400000,15,15,7,25.95
922,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db749,2009-10-17 00:00:00,1257033600000,11,0,1,19.99
929,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db758,2009-10-24 00:00:00,1257638400000,No Rank,11,2,19.99
957,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db789,2009-11-07 00:00:00,1258848000000,15,0,3,19.99
965,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db799,2009-11-14 00:00:00,1259452800000,11,15,4,19.99
980,http://www.amazon.com/Heat-Wave-Nikki-Book-ebo...,Richard Castle,Descr: An N.Y.P.D. homicide detective investig...,Hyperion,HEAT WAVE,5b4aa4ead3089013507db7b0,2009-11-21 00:00:00,1260057600000,14,11,5,19.99
1062,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \nElvis Cole and his partner, Joe Pike,...",Penguin Group (USA) Incorporated,THE FIRST RULE,5b4aa4ead3089013507db844,2010-01-17 00:00:00,1264896000000,2,0,1,26.95
1080,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db85b,2010-01-24 00:00:00,1265500800000,5,2,2,26.95
1093,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db86f,2010-01-31 00:00:00,1266105600000,5,5,3,26.95
1114,http://www.amazon.com/The-First-Rule-Pike-Nove...,Robert Crais,"Descr: \n\nElvis Cole and his partner, Joe Pik...",Putnam,THE FIRST RULE,5b4aa4ead3089013507db88a,2010-02-07 00:00:00,1266710400000,12,5,4,26.95
1442,http://www.amazon.com/Cure-Robin-Cook/dp/03991...,Robin Cook,Descr: \nA New York City medical examiner atte...,Putnam,CURE,5b4aa4ead3089013507dbaa8,2010-08-15 00:00:00,1283040000000,14,0,1,26.95
1530,http://www.amazon.com/Naked-Heat-Nikki-Richard...,Richard Castle,Descr: Nikki Heat’s latest murder investigatio...,Hyperion,NAKED HEAT,5b4aa4ead3089013507dbb2d,2010-10-03 00:00:00,1287273600000,7,0,1,24.99
1549,http://www.amazon.com/Naked-Heat-Nikki-Richard...,Richard Castle,Descr: Nikki Heat’s latest murder investigatio...,Hyperion,NAKED HEAT,5b4aa4ead3089013507dbb4a,2010-10-10 00:00:00,1287878400000,16,7,2,24.99
1575,http://www.amazon.com/The-Templar-Salvation-Ra...,Raymond Khoury,Descr: A secret history of the infamous Templa...,Dutton,THE TEMPLAR SALVATION,5b4aa4ead3089013507dbb72,2010-10-24 00:00:00,1289088000000,16,0,1,26.95
1717,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,"Descr: Joe Pike and Elvis Cole, Hollywood priv...",Putnam,THE SENTRY,5b4aa4ead3089013507dbc54,2011-01-16 00:00:00,1296345600000,2,0,1,26.95
1733,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,"Descr: Joe Pike and Elvis Cole, Hollywood priv...",Putnam,THE SENTRY,5b4aa4ead3089013507dbc6b,2011-01-23 00:00:00,1296950400000,5,2,2,26.95
1748,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbc82,2011-01-30 00:00:00,1297555200000,8,5,3,26.95
1763,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbc99,2011-02-05 00:00:00,1298160000000,11,8,4,26.95
1778,http://www.amazon.com/The-Sentry-Joe-Pike-Nove...,Robert Crais,Descr: The former cop Joe Pike finds that a pa...,Putnam,THE SENTRY,5b4aa4ead3089013507dbcb0,2011-02-12 00:00:00,1298764800000,No Rank,11,5,26.95
2147,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf23,2011-09-24 00:00:00,1318118400000,1,0,1,25.99
2167,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf40,2011-10-01 00:00:00,1318723200000,10,1,2,25.99
2191,http://www.amazon.com/Heat-Rises-Nikki-Richard...,Richard Castle,Descr: An N.Y.P.D. homicide detective uncovers...,Hyperion,HEAT RISES,5b4aa4ead3089013507dbf6a,2011-10-15 00:00:00,1319932800000,12,0,3,25.99
2350,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc08b,2012-01-28 00:00:00,1329004800000,1,0,1,26.95
2364,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0a1,2012-02-04 00:00:00,1329609600000,3,1,2,26.95
2370,http://www.amazon.com/The-Fear-Index-Robert-Ha...,Robert Harris,Descr: A billionaire hedge fund manager in Gen...,Knopf,THE FEAR INDEX,5b4aa4ead3089013507dc0aa,2012-02-04 00:00:00,1329609600000,12,0,1,25.95
2378,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0ba,2012-02-11 00:00:00,1330214400000,8,3,3,26.95
2384,http://www.amazon.com/The-Fear-Index-Robert-Ha...,Robert Harris,Descr: A billionaire hedge fund manager in Gen...,Knopf,THE FEAR INDEX,5b4aa4ead3089013507dc0c1,2012-02-11 00:00:00,1330214400000,15,12,2,25.95
2394,http://www.amazon.com/Taken-Elvis-Cole-Robert-...,Robert Crais,Descr: It’s Joe Pike to the rescue when Elvis ...,Putnam,TAKEN,5b4aa4ead3089013507dc0d4,2012-02-18 00:00:00,1330819200000,14,8,4,26.95
2469,http://www.amazon.com/The-Cove-Novel-Ron-Rash/...,Ron Rash,Descr: Intrigue in backwoods North Carolina du...,Ecco/HarperCollins,THE COVE,5b4aa4ead3089013507dc176,2012-04-14 00:00:00,1335657600000,16,0,1,26.99
2536,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc1e6,2012-05-26 00:00:00,1339286400000,8,0,1,27.99
2546,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc1fe,2012-06-02 00:00:00,1339891200000,12,8,2,27.99
2559,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc216,2012-06-09 00:00:00,1340496000000,16,12,3,27.99
2563,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc220,2012-06-16 00:00:00,1341100800000,6,16,4,27.99
2571,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc233,2012-06-23 00:00:00,1341705600000,5,6,5,27.99
2582,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc24b,2012-06-30 00:00:00,1342310400000,9,5,6,27.99
2594,http://www.amazon.com/Canada-Richard-Ford-eboo...,Richard Ford,Descr: A boy takes refuge in Saskatchewan afte...,Ecco/HarperCollins Publishers,CANADA,5b4aa4ead3089013507dc262,2012-07-07 00:00:00,1342915200000,12,9,7,27.99
2692,http://www.amazon.com/Frozen-Heat-Nikki-Richar...,Richard Castle,Descr: The N.Y.P.D. homicide detective Nikki H...,Hyperion,FROZEN HEAT,5b4aa4ead3089013507dc326,2012-09-15 00:00:00,1348963200000,8,0,1,26.99
2891,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc49d,2013-01-26 00:00:00,1360454400000,3,0,1,27.95
2905,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4b4,2013-02-02 00:00:00,1361059200000,No Rank,3,2,27.95
2918,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4c9,2013-02-09 00:00:00,1361664000000,No Rank,6,3,27.95
2930,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4dd,2013-02-16 00:00:00,1362268800000,7,7,4,27.95
2945,http://www.amazon.com/Suspect-Robert-Crais-ebo...,Robert Crais,Descr: A Los Angeles policeman and a German sh...,Putnam,SUSPECT,5b4aa4ead3089013507dc4f7,2013-02-23 00:00:00,1362873600000,13,7,5,27.95

Podemos también guardar nuestras condiciones en variables y después utilizarlos, por ejemplo, encuentra todas las producciones cuyo precio es mayor a 20:

In [9]:
mayor_a_20 = df["price.numberDouble"] > 20

In [10]:
df[mayor_a_20].head(3)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
0,http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Descr: Aliens have taken control of the minds ...,"Little, Brown",THE HOST,5b4aa4ead3089013507db18c,2008-05-24 00:00:00,1212883200000,2,1,3,25.99
1,http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,Descr: A woman's happy marriage is shaken when...,St. Martin's,LOVE THE ONE YOU'RE WITH,5b4aa4ead3089013507db18d,2008-05-24 00:00:00,1212883200000,3,2,2,24.95
2,http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,Descr: A Massachusetts state investigator and ...,Putnam,THE FRONT,5b4aa4ead3089013507db18e,2008-05-24 00:00:00,1212883200000,4,0,1,22.95

Podemos incluso aplicar dos o más filtros utilizando `operadores lógicos`. En este caso, nuestro operador `and` se representa con un `&` y el operador `or` se representa con `|`.

Así que podemos obtener todas las producciones con rango 1 y que además cuyo precio sea mayor a 20:

In [13]:
rank_numero_uno = df["rank.numberInt"] == '1'

In [14]:
df[mayor_a_20 & rank_numero_uno].head(3)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
51,http://www.amazon.com/Fearless-Fourteen-Janet-...,Janet Evanovich,Descr: Stephanie Plum and her boyfriend Joe Mo...,St. Martin’s,FEARLESS FOURTEEN,5b4aa4ead3089013507db1db,2008-06-21 00:00:00,1215302400000,1,0,1,27.95
63,http://www.amazon.com/Fearless-Fourteen-Janet-...,Janet Evanovich,Descr: Stephanie Plum and her boyfriend Joe Mo...,St. Martin’s,FEARLESS FOURTEEN,5b4aa4ead3089013507db1ef,2008-06-28 00:00:00,1215907200000,1,1,2,27.95
85,http://www.amazon.com/Tribute-Nora-Roberts/dp/...,Nora Roberts,Descr: A former child star returns to Virginia...,Putnam,TRIBUTE,5b4aa4ead3089013507db217,2008-07-12 00:00:00,1217116800000,1,0,1,26.95

In [21]:
filtro = (df["price.numberDouble"] > 20) & (df["rank.numberInt"] == '1') # necesita paréntesis para asociar primero las operaciones boolenas

In [22]:
df[filtro].head(3)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
51,http://www.amazon.com/Fearless-Fourteen-Janet-...,Janet Evanovich,Descr: Stephanie Plum and her boyfriend Joe Mo...,St. Martin’s,FEARLESS FOURTEEN,5b4aa4ead3089013507db1db,2008-06-21 00:00:00,1215302400000,1,0,1,27.95
63,http://www.amazon.com/Fearless-Fourteen-Janet-...,Janet Evanovich,Descr: Stephanie Plum and her boyfriend Joe Mo...,St. Martin’s,FEARLESS FOURTEEN,5b4aa4ead3089013507db1ef,2008-06-28 00:00:00,1215907200000,1,1,2,27.95
85,http://www.amazon.com/Tribute-Nora-Roberts/dp/...,Nora Roberts,Descr: A former child star returns to Virginia...,Putnam,TRIBUTE,5b4aa4ead3089013507db217,2008-07-12 00:00:00,1217116800000,1,0,1,26.95

---
---

## Reto 5: Filtros

### 1. Objetivos:
    - Practicar el uso de filtros para la obtención de subconjuntos de datos
    
### 2. Desarrollo:

#### a) Filtrando por fechas, booleanos y valores numéricos

Vamos a trabajar con el mismo dataset que guardaste del Reto anterior. Este Reto consiste en los siguiente:

Usando filtros, crea 3 subconjuntos de datos:

1. Un subconjunto llamado `df_hazardous` que contenga sólo los records que correspondan a los objetos donde `is_potentially_hazardous_asteroid` sea `True` (o `1`).
2. Un subconjunto llamado `df_greater_than_1000` que contenga sólo los records donde el `estimated_diameter.meters.estimated_diameter_max` sea mayor a 1000 metros.
3. Un subconjunto llamado `df_february` que contenga sólo los records que pertenezcan exactamente al mes de Febrero de 1995. Recuerda que los datos en la columna `epoch_date_close_approach` están en milisegundos.

In [91]:
df_reto_5 = pd.read_csv("../Ejemplo-04/objetos_cercanos_4.csv", index_col=0)
df_reto_5.head(3)

,Unnamed: 0.1,Unnamed: 0.1.1,id_name,is_potentially_hazardous_asteroid,estimated_diameter.meters.estimated_diameter_min,estimated_diameter.meters.estimated_diameter_max,close_approach_date,epoch_date_close_approach,orbiting_body,relative_velocity.kilometers_per_second,relative_velocity.kilometers_per_hour,orbit_class_description,id,name,relative_velocity.kilometers_per_minute,proportion_of_max_diameter_to_earth
0,0,0,2154652-154652 (2004 EP20),0,483.676488,1081.533507,1995-01-07,1995-01-07 08:33:00,Earth,16.142864,58114.308667,Near Earth asteroid orbits similar to that of ...,2154652,154652 (2004 EP20),968.571811,0.000085
1,1,1,3153509-(2003 HM),1,96.506147,215.794305,1995-01-07,1995-01-07 15:09:00,Earth,12.351044,44463.757734,Near Earth asteroid orbits which cross the Ear...,3153509,(2003 HM),741.062629,0.000017
2,2,2,3516633-(2010 HA),0,44.111820,98.637028,1995-01-07,1995-01-07 02:47:00,Earth,6.220435,NaN,Near Earth asteroid orbits similar to that of ...,3516633,(2010 HA),NaN,0.000008

In [92]:
df_reto_5.dtypes

Unnamed: 0.1                                          int64
Unnamed: 0.1.1                                        int64
id_name                                              object
is_potentially_hazardous_asteroid                     int64
estimated_diameter.meters.estimated_diameter_min    float64
estimated_diameter.meters.estimated_diameter_max    float64
close_approach_date                                  object
epoch_date_close_approach                            object
orbiting_body                                        object
relative_velocity.kilometers_per_second             float64
relative_velocity.kilometers_per_hour               float64
orbit_class_description                              object
id                                                    int64
name                                                 object
relative_velocity.kilometers_per_minute             float64
proportion_of_max_diameter_to_earth                 float64
dtype: object

In [93]:
df_hazardous = df_reto_5[ df_reto_5["is_potentially_hazardous_asteroid"] == 1 ]

In [94]:
df_bigger_than_1000 = df_reto_5[ df_reto_5["estimated_diameter.meters.estimated_diameter_max"] > 1000 ]

In [67]:
#df_reto_5["epoch_date_close_approach"] = pd.to_datetime(df_reto_5["epoch_date_close_approach"])

In [68]:
#df_reto_5.dtypes

Unnamed: 0.1                                                 int64
Unnamed: 0.1.1                                               int64
id_name                                                     object
is_potentially_hazardous_asteroid                            int64
estimated_diameter.meters.estimated_diameter_min           float64
estimated_diameter.meters.estimated_diameter_max           float64
close_approach_date                                         object
epoch_date_close_approach                           datetime64[ns]
orbiting_body                                               object
relative_velocity.kilometers_per_second                    float64
relative_velocity.kilometers_per_hour                      float64
orbit_class_description                                     object
id                                                           int64
name                                                        object
relative_velocity.kilometers_per_minute                    float64
proportion_of_max_diameter_to_earth                        float64
dtype: object

In [95]:
#df_reto_5[ df_reto_5["epoch_date_close_approach"] > 1000 ]
df_february = df_reto_5[  (pd.DatetimeIndex(df_reto_5["epoch_date_close_approach"]).year == 1995) & (pd.DatetimeIndex(df_reto_5["epoch_date_close_approach"]).month == 2) ]

In [98]:
def fecha_to_timespam(fecha):
    import time
    import datetime
    
    return time.mktime(datetime.datetime.strptime(fecha,"%Y-%m-%d %H:%M:%S").timetuple())

df_reto_5["epoch_date_close_approach"] = df_reto_5["epoch_date_close_approach"].map(fecha_to_timespam)

In [99]:
df_reto_5

,Unnamed: 0.1,Unnamed: 0.1.1,id_name,is_potentially_hazardous_asteroid,estimated_diameter.meters.estimated_diameter_min,estimated_diameter.meters.estimated_diameter_max,close_approach_date,epoch_date_close_approach,orbiting_body,relative_velocity.kilometers_per_second,relative_velocity.kilometers_per_hour,orbit_class_description,id,name,relative_velocity.kilometers_per_minute,proportion_of_max_diameter_to_earth
0,0,0,2154652-154652 (2004 EP20),0,483.676488,1081.533507,1995-01-07,789485580.0,Earth,16.142864,58114.308667,Near Earth asteroid orbits similar to that of ...,2154652,154652 (2004 EP20),968.571811,0.000085
1,1,1,3153509-(2003 HM),1,96.506147,215.794305,1995-01-07,789509340.0,Earth,12.351044,44463.757734,Near Earth asteroid orbits which cross the Ear...,3153509,(2003 HM),741.062629,0.000017
2,2,2,3516633-(2010 HA),0,44.111820,98.637028,1995-01-07,789464820.0,Earth,6.220435,NaN,Near Earth asteroid orbits similar to that of ...,3516633,(2010 HA),NaN,0.000008
3,3,3,3837644-(2019 AY3),0,46.190746,103.285648,1995-01-07,789531900.0,Earth,22.478615,80923.015021,Near Earth asteroid orbits similar to that of ...,3837644,(2019 AY3),1348.716917,0.000008
4,4,4,3843493-(2019 PY),0,22.108281,49.435619,1995-01-07,789464700.0,Earth,4.998691,17995.288355,Near Earth asteroid orbits similar to that of ...,3843493,(2019 PY),299.921473,0.000004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,328,328,2267136-267136 (2000 EF104),0,441.118200,986.370281,1995-02-21,793358220.0,Earth,16.180392,58249.410194,Near Earth asteroid orbits similar to that of ...,2267136,267136 (2000 EF104),970.823503,0.000077
329,329,329,3360486-(2006 WE4),0,441.118200,986.370281,1995-02-21,793399440.0,Earth,15.106140,54382.104639,Near Earth asteroid orbits which cross the Ear...,3360486,(2006 WE4),906.368411,0.000077
330,330,330,3656919-(2014 BG3),0,160.160338,358.129403,1995-02-21,793386480.0,Earth,20.343173,73235.423517,An asteroid orbit contained entirely within th...,3656919,(2014 BG3),1220.590392,0.000028
331,331,331,3803762-(2018 GY4),0,421.264611,941.976306,1995-02-21,793389240.0,Earth,29.732426,107036.733058,Near Earth asteroid orbits similar to that of ...,3803762,(2018 GY4),1783.945551,0.000074
332,332,332,3989652-(2020 CH1),0,21.525586,48.132673,1995-02-21,793422900.0,Earth,6.998083,NaN,Near Earth asteroid orbits similar to that of ...,3989652,(2020 CH1),NaN,0.000004

In [100]:
def checar_subconjuntos(df_february, df_hazardous, df_bigger_than_1000):
    
    import pandas as pd
    import base64

    datos = b'CmFzc2VydCAoZGZfaGF6YXJkb3VzWydpc19wb3RlbnRpYWxseV9oYXphcmRvdXNfYXN0ZXJvaWQnXSA9PSAwKS5zdW0oKSA9PSAwLCAnQWxndW5vcyByZWNvcmRzIGVuIGBkZl9oYXphcmRvdXNgIHBlcnRlbmVjZW4gYSBvYmpldG9zIGRvbmRlIGlzX3BvdGVudGlhbGx5X2hhemFyZG91c19hc3Rlcm9pZCBlcyBgRmFsc2VgJwphc3NlcnQgKGRmX2hhemFyZG91c1snaXNfcG90ZW50aWFsbHlfaGF6YXJkb3VzX2FzdGVyb2lkJ10gPT0gMSkuc3VtKCkgPiAwLCAnTm8gaGF5IG5pbmd1biByZWNvcmQgZW4gYGRmX2hhemFyZG91c2AgZG9uZGUgaXNfcG90ZW50aWFsbHlfaGF6YXJkb3VzX2FzdGVyb2lkIHNlYSBgVHJ1ZWAnCgphc3NlcnQgKGRmX2JpZ2dlcl90aGFuXzEwMDBbJ2VzdGltYXRlZF9kaWFtZXRlci5tZXRlcnMuZXN0aW1hdGVkX2RpYW1ldGVyX21heCddIDw9IDEwMDApLnN1bSgpID09IDAsICdBbGd1bm9zIHJlY29yZHMgZW4gYGRmX2JpZ2dlcl90aGFuXzEwMDBgIHBlcnRlbmVjZW4gYSBvYmpldG9zIGNvbiBkacOhbWV0cm8gbWVub3IgYSAxMDAwIG1ldHJvcycKYXNzZXJ0IChkZl9iaWdnZXJfdGhhbl8xMDAwWydlc3RpbWF0ZWRfZGlhbWV0ZXIubWV0ZXJzLmVzdGltYXRlZF9kaWFtZXRlcl9tYXgnXSA+IDEwMDApLnN1bSgpID4gMCwgJ05vIGhheSBuaW5nw7puIHJlY29yZCBlbiBgZGZfYmlnZ2VyX3RoYW5fMTAwMGAgcXVlIHBlcnRlbmV6Y2EgYSBvYmpldG9zIGNvbiBkacOhbWV0cm8gbWF5b3IgYSAxMDAwIG1ldHJvcycKCmZlYnJ1YXJ5ID0gcGQudG9fZGF0ZXRpbWUoJzE5OTUtMDItMDEnLCBmb3JtYXQ9JyVZLSVtLSVkJykudGltZXN0YW1wKCkgKiAxMDAwCm1hcmNoID0gcGQudG9fZGF0ZXRpbWUoJzE5OTUtMDMtMDEnLCBmb3JtYXQ9JyVZLSVtLSVkJykudGltZXN0YW1wKCkgKiAxMDAwIAoKYXNzZXJ0IChkZl9mZWJydWFyeVsnZXBvY2hfZGF0ZV9jbG9zZV9hcHByb2FjaCddIDwgZmVicnVhcnkpLnN1bSgpID09IDAsICdBbGd1bm9zIHJlY29yZHMgZGUgYGRmX2ZlYnJ1YXJ5YCBwZXJ0ZW5lY2VuIGEgbWVzZXMgYW50ZXJpb3JlcyBhIEZlYnJlcm8gZGUgMTk5NScKYXNzZXJ0IChkZl9mZWJydWFyeVsnZXBvY2hfZGF0ZV9jbG9zZV9hcHByb2FjaCddID49IG1hcmNoKS5zdW0oKSA9PSAwLCAnQWxndW5vcyByZWNvcmRzIGRlIGBkZl9mZWJydWFyeWAgcGVydGVuZWNlbiBhIG1lc2VzIHBvc3RlcmlvcmVzIGEgRmVicmVybyBkZSAxOTk1Jwo='
    eval(compile(base64.b64decode(datos), "", "exec"), globals())
    
    print('Todos tus subconjuntos son correctos. ¡Gran trabajo!')
    
checar_subconjuntos(df_february, df_hazardous, df_bigger_than_1000)

TypeError: '<' not supported between instances of 'str' and 'float'